name: alu-student-companion

services:
  # Backend service
  - type: web
    name: alu-companion-api
    runtime: python
    pythonVersion: 3.11
    region: ohio
    plan: free
    buildCommand: pip install -r backend/requirements-deploy.txt
    startCommand: cd backend && python -c "import torch; torch.set_num_threads(1)" && uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: ./backend
      - key: ENVIRONMENT
        value: production
      - key: CORS_ALLOWED_ORIGINS
        value: https://alu-companion.onrender.com
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers_cache
      - key: OMP_NUM_THREADS
        value: 1
      - key: MKL_NUM_THREADS  
        value: 1
      
  # Frontend service  
  - type: web
    name: alu-companion
    runtime: node
    nodeVersion: 18.x
    region: ohio
    plan: free
    buildCommand: npm ci --production && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://alu-companion-api.onrender.com
