# Blueprint name
name: alu-student-companion

services:
  # Backend service
  - type: web
    name: alu-companion-api
    runtime: python
    pythonVersion: 3.11
    region: ohio
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: ENVIRONMENT
        value: production
      - key: OPENAI_API_KEY
        sync: false
        required: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://alu-companion.onrender.com

  # Frontend service
  - type: web
    name: alu-companion
    runtime: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://alu-companion-api.onrender.com