name: alu-student-companion

services:
  # Backend service
  - type: web
    name: alu-companion-api
    runtime: python
    pythonVersion: 3.11
    region: ohio
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: ./backend
      - key: ENVIRONMENT
        value: production
      - key: CORS_ALLOWED_ORIGINS
        value: https://alu-companion.onrender.com
      
  # Frontend service
  - type: web
    name: alu-companion
    runtime: node
    nodeVersion: 18.x
    region: ohio
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://alu-companion-api.onrender.com
