
services:
  # Backend API service
  - type: web
    name: alu-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 8000
    autoDeploy: true
    healthCheckPath: /

  # Frontend service (if you want to deploy the frontend directly to Render)
  # - type: web
  #   name: alu-chatbot-frontend
  #   env: static
  #   buildCommand: npm install && npm run build
  #   staticPublishPath: ./dist
  #   routes:
  #     - type: rewrite
  #       source: /*
  #       destination: /index.html
  #   envVars:
  #     - key: VITE_BACKEND_URL
  #       fromService:
  #         name: alu-chatbot-backend
  #         type: web
  #         envVarKey: RENDER_EXTERNAL_URL
